services:
  backend:
    build: .
    container_name: utech_backend_trivia
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - EXTERNAL_API_URL=https://tryvia.ptr.red/api.php?amount=100